# Generated by Django 4.1.2 on 2022-11-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
