# Generated by Django 4.1.2 on 2022-12-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todos', '0002_todos_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Todos',
        ),
    ]
